### ISSUE TITLE
Make the README examples work using files in the repo

### ISSUE THREAD

**Issue by taldcroft** [cds-astro/cds.pyreadme#3]
Currently the README examples rely on fictitious files like `file.csv` or `table.vot`. This makes it difficult to try out the examples. If example files were placed in a directory (for example `examples`), then it would be possible for the user to copy/paste all the examples and more quickly understand how to use the package.

**Comment by gilleslandais** [comment]
You are true!
I modified the README and add the `table.vot` in the `tests` repository.

**Comment by taldcroft** [comment]
Probably also worth noting in the README that the example files are in the `tests` directory.
