### ISSUE TITLE
Install fail due to problems with logging module

### ISSUE THREAD

**Issue by pmaxted** [cds-astro/cds.pyreadme#4]
```
 % pip install git+git://github.com/cds-astro/cds.pyreadme.git
```
fails due to a problem with installing the dependency "logging" from pypi. 
Is this dependency needed? I though logging was included already in any recent version of python.

**Comment by gilleslandais** [comment]
you are true - I will update the package -
next version will include an other issue related to unit -

**Comment by gilleslandais** [comment]
the new version is available in pip -
pip install cdspyreadme
