### ISSUE TITLE
makeReadMe() fails when columns contain NaN values, writeCDSTables() replaces NaN values with zero.

### ISSUE THREAD

**Issue by mphanderson** [cds-astro/cds.pyreadme#7]
Hi, I have some astropy tables which I am converting into CDS tables for upload. Some of the physical quantities for my table entries are missing, and those array elements are filled with NaNs.

The writeCDSTables() runs without crashing, but replaces all NaN values with 0 (this is problematic).

The makeReadMe() crashes and returns: `ValueError: cannot convert float NaN to integer`, and hence does not generate an output.

Is there a way for NaN values to be supported?

Many thanks.

Version: 1.3.4

**Comment by gilleslandais** [comment]
Hello -
there are different ways: you can use the astropy MaskedColumn to remove NaN or use the nullvalue parameter in the CDSTablesMaker.addtable(...) method

it seems that it depends of the input format  .. Do you have an example ? what is the format that you use in input: CSV, FITS other?

**Comment by mphanderson** [comment]
Hi, thank you for your suggestions. By converting the astropy Columns with NaNs to MaskedColumn (with NaNs masked) I now avoid the errors, and I get an expected table/ReadMe output.
